// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdijbuywftptemwnvuuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkaWpidXl3ZnRwdGVtd252dXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NzAwNTgsImV4cCI6MjA1MDE0NjA1OH0.PmcaM61s2fxoHF113Qduo_N-So1-4m9yF75_RtePyIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);